### ISSUE TITLE
Implementation proposal

### ISSUE THREAD

**Issue by Rusenche** [NeverDecaf/chromium-web-store#124]
@NeverDecaf

Implementation proposal

`Chromium web store` is great.

But I have a suggestion and I hope you will implement it.

I am attaching a photo:
![available update](https://github.com/NeverDecaf/chromium-web-store/assets/18578128/07b610e7-74dc-4a2f-9c47-10d05335539c)

It appears that there are updates available. Currently - it is not clear the criteria by which these available updates are ordered. Because the criterion is certainly not in alphabetical order.

From memory from yesterday - there were only 4 update suggestions and again from memory - as if the update suggestion that is from today is `Cookie consent popup blocker`. In reality, it is located penultimate. Why is it there and not at the top - as the latest offering with an update available...

**My suggestion is - the topmost extension should be the extension whose update came just now or 1 minutes/10 minutes ago. The bottommost extension - whose update is the oldest.**

**Comment by NeverDecaf** [comment]
The list of available updates is populated asynchronously as each server responds*. However, 99% of the updates are going to be from google, and therefore batched in a single request. It would be fairly simple to sort these batched updates alphabetically but sorting them by update time isn't simple as the xml returned by google does not include any data about the update time. Here is an example: [https://clients2.google.com/service/update2/crx?response=updatecheck&acceptformat=crx2,crx3&prodversion=76.0.3809.100&x=id%3Dogfcmafjalglgifnmanfmnieipoejdcf%26uc](https://clients2.google.com/service/update2/crx?response=updatecheck&acceptformat=crx2,crx3&prodversion=76.0.3809.100&x=id%3Dogfcmafjalglgifnmanfmnieipoejdcf%26uc)
Without this data the only option I can think of is to save the order locally (and somewhat arbitrarily) based on when the users browser checks for updates, this would somewhat alleviate your specific situation by putting the new update at the top of the list. However, this solution is significantly more involved and I'm not sure when I'll find time to implement it, especially since I'm not happy with it at all and would prefer something that reflects the actual, real update time.

*This means that truly ordering *all* updates including ones from outside the chrome web store would be still more involved.

**Comment by Rusenche** [comment]
I think my proposal is good. The thing about implementing it is that you will find it quite difficult and time consuming, if at all possible to have a sort by date of occurrence of updates. It probably is.

I've been backing up my Ungoogled Chromium settings indefinitely. I almost never update any extension immediately when an available update becomes available.

And since there have been 6-7 total updates available since I posted this thread, I mistakenly installed them all, trusting that the available extension updates were normal for users.

It turned out not to be. A recent example from yesterday, when I updated all available extensions, is that the `Save image by right click: PNG, JPG, or WebP` extension has practically become a kind of malicious extension with its new version. I missed reading the comments https://chrome.google.com/webstore/detail/save-image-by-right-click/hhmnengcgekecnlielgcfcbjanjlnifg/

Why I'm writing all this ... maybe it's a tip to everyone how not to trust extension updates provided. Thanks to the backups I made - I went back to a period before installing all these extensions and did not install only one that I wrote about above.

Thanks to your great extension - I've marked not to check in the future for updates to the malicious extension, which is effectively already malicious.

In effect, if it's not your awesome extension, users have no protection from their extension updates, because extension updates install themselves and users have no control - there's no control to refuse to install updates, and no control to ignore an update of an extension, while with your extension it is possible to create a crx of each extension when it is installed and thus we have a kind of archive, because there are extensions that do not have public versions published, through which we can go back one or several at a time -early versions. Your extension provides all these useful features and is therefore the icing on the cake. :}
