### ISSUE TITLE
Opera store support

### ISSUE THREAD

**Issue by JAKill02** [NeverDecaf/chromium-web-store#136]
Hi all. I would like to ask you to improve the ability to install from the Opera Store.
The button is there, but the installation does not work. This would greatly help extend the life of old browsers that can only use Manifest v2. and in general, the Opera Store may well become an alternate airfield. Quite possible Opera, like Mozilla, will not put pressure on the Manifest v2 add-ons.
Besides, we already install add-ons manually from the Opera store, so why not make this process easier?

![Opera store](https://github.com/NeverDecaf/chromium-web-store/assets/55640282/48befa82-f31d-44b4-a0f1-f10797fd9098)

tested in the Centbrowser with the 102 Chromium engine and the "Chromium Web Store
1.5.4.1"

**Comment by JAKill02** [comment]
in principle, to initiate installation from the Opera Store (**if the browser supports installation immediately**, _otherwise it offers to download the add-on_) you just need to change and activate the address bar like this
number 1: original.
number 2: **line initiating installation/download of the add-on**

1: https://addons.opera.com/ru/extensions/details/savefromnet-helper/
2: **https://addons.opera.com/extensions/download/savefromnet-helper/**

**Comment by NeverDecaf** [comment]
What are you describing is what `chromium-web-store` already does. When I click that button in the opera store, the crx is downloaded from the second url you listed. The reason why I don't just open `https://addons.opera.com/extensions/download/savefromnet-helper/` in a new tab is because the opera CRX format is not compatible with chromium. If I navigate to that download url in chromium, I only get this banner:
![image](https://github.com/NeverDecaf/chromium-web-store/assets/19150416/4a2d5f30-0b4e-4172-9a45-06015cecf088)
My only option is to download the CRX, unpack it, and load the extension via `Load unpacked` in developer mode. This is why the default for the opera store is to save the file instead of just open the url. If this isn't happening on your browser it may differ somehow from chromium, if you are seeing some error output in the console or in `chrome://extensions` that would help diagnose the issue.

One thing which may solve this for you is to modify `scripts/util.js` [line 120](https://github.com/NeverDecaf/chromium-web-store/blob/703a907aedae4d5e6a2171b177f8aad690ca1889/src/scripts/util.js#L120) and change:
`manualInstallDownloadUrl: crx_url,` to `newTabUrl: crx_url,`. This change *should* cause the behavior you want (opening the download url in a new tab).

**Comment by JAKill02** [comment]
yes, it helped! - **thanks a lot**
Now a pop-up window appears offering to install any add-on from the Opera store.

CentBrowser is generally an omnivorous thing; if it can install something, it does it, the main thing is to give it to him.

![Opera store 03](https://github.com/NeverDecaf/chromium-web-store/assets/55640282/9c336f97-534f-42d3-be26-4e29290672d1)

Now I will repack all the next versions of the "Chromium Web Store" for myself under CentBrowser, of course, if you yourself do not release such special versions for browsers that can perform similar installations.

[Chromium.Web.Store v1.5.4.1 - CentBrowser ver.zip](https://github.com/NeverDecaf/chromium-web-store/files/13573957/Chromium.Web.Store.v1.5.4.1.-.CentBrowser.ver.zip)

and without this change, the install button in the Opera store for my browser was just a toy, no swearing in the console, just silence. With this behavior, you cannot download the add-on either.

**Comment by JAKill02** [comment]
It’s sad to say, but it turned out that, being repackaged, the add-on Chromium.Web.Store loses the ability to install add-ons from the New Chrome Store (The install button becomes gray and inactive). and I can't do anything about it. Something happens during the packaging phase of the add-on.

being simply downloaded as a folder with files, everything works well.

one hope is that **NeverDecaf** itself will release a version of Chromium.Web.Store for browsers like CentBrowser, with their installation features from the Opera Store

**Comment by NeverDecaf** [comment]
I believe this happens because the extension id was hardcoded and repacking the extension generates a new id. I've added a fix in the latest commit; you'll have to package it from [src](https://github.com/NeverDecaf/chromium-web-store/tree/master/src) to try it out.

**Comment by JAKill02** [comment]
> I believe this happens because the extension id was hardcoded and repacking the extension generates a new id. I've added a fix in the latest commit; you'll have to package it from [src](https://github.com/NeverDecaf/chromium-web-store/tree/master/src) to try it out.

yes, the packaging from SRC version 1.5.4 worked.
but not from release SRC 1.5.4.1.

so for now our current version is 1.5.4   [Chromium.Web.Store v1.5.4 (src) CentBrowser ver.zip](https://github.com/NeverDecaf/chromium-web-store/files/13628994/Chromium.Web.Store.v1.5.4.src.CentBrowser.ver.zip) _(archive with .crx file inside)_

**Comment by JAKill02** [comment]
well, yeah, now it’s possible to make it from 1.5.4.1
[Chromium.Web.Store v1.5.4.1 (src) CentBrowser ver.zip](https://github.com/NeverDecaf/chromium-web-store/files/13629108/Chromium.Web.Store.v1.5.4.1.src.CentBrowser.ver.zip) _(archive with .crx file inside)_

**Comment by JAKill02** [comment]
version for browsers on old Chromium engines to support the new version of the Chrome store, which also has the ability to install add-ons from the Opera store directly

tested on Cent Browser Version 4.2.10.171 (Official build), (32 bit) (portable) (Chromium 80.0.3987.163)

[Chromium.Web.Store v1.4.5 (src) CentBrowser ver (manifest v2 browsers).zip](https://github.com/NeverDecaf/chromium-web-store/files/14300822/Chromium.Web.Store.v1.4.5.src.CentBrowser.ver.manifest.v2.browsers.zip) _(archive with .crx file inside)_

**Comment by JAKill02** [comment]
upd
[Chromium.Web.Store v1.5.4.2 (src) CentBrowser ver.zip](https://github.com/NeverDecaf/chromium-web-store/files/14483074/Chromium.Web.Store.v1.5.4.2.src.CentBrowser.ver.zip) _(archive with .crx file inside)_
