### ISSUE TITLE
Update not functioning anymore

### ISSUE THREAD

**Issue by kinoegit** [NeverDecaf/chromium-web-store#145]
I'm using latest version of ungoogled Chromium with firejail sandbox.
Updates are announced as usual, clicking on name of extension formerly started update.
Now clicking only opens a new tab (in background). Then nothing happens until the new tab is manually closed then update seems to be downloaded into download folder. Thats it! Nothing else happens.
I can manually update the downloded extension by drag 'n drop into chrome://extensions/. 
The following is set:
> If you are using ungoogled-chromium: You must change the flag chrome://flags/#extension-mime-request-handling to Always prompt for install.
The following is unset:
> If you are NOT using ungoogled-chromium: Ensure the following option is checked: Extension Options (chrome://extensions/?options=ocaahdebbfolfmndjeplogmgcagdmblk) > Advanced > Always download CRX files

What I tried to no avail: disabled all non relevant extensions, started update by right click 'update all extensions'

![noupdate](https://github.com/NeverDecaf/chromium-web-store/assets/18682867/9fc82138-d503-486a-8b26-07d547da127a)

**Comment by ThisNekoGuy** [comment]
I get a similar issue with Ungoogled Chromium too; extensions are set to download to a folder instead rather than just updating like they normally should as per the directions in the readme lead users to normally experience.
Something is amiss.

**Comment by NeverDecaf** [comment]
Which version of UGC? I can't reproduce this on 122.0.6261.56

**Comment by ThisNekoGuy** [comment]
121.0.6167.184 - It's what's currently served by [flathub](121.0.6167.184) for Linux distributions as a Linux agnostic package.

**Comment by sequilox** [comment]
I can reproduce this issue with the following version:
121.0.6167.184 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

**Comment by kinoegit** [comment]
Version 121.0.6167.184 (Official Build, ungoogled-chromium) Arch Linux (64-Bit)

**Comment by kinoegit** [comment]
> Which version of UGC? I can't reproduce this on 122.0.6261.56

Version 121.0.6167.184 (Official Build, ungoogled-chromium) Arch Linux (64-Bit)

**Comment by kinoegit** [comment]
Sometimes update via rightclick does function! But i can't say when. Downloaded extensions remain in download folder anyway. Is this intended?

**Comment by vodkapmp** [comment]
> Sometimes update via rightclick does function!? Downloaded extensions remain in download folder anyway. Is this intended?

I seem to be able to update the extensions by right clicking the icon for chromium-web-store, and clicking update all.
Though I have to click the "Add extension" button 20-30 times before anything happens.
`Version 121.0.6167.184 (Official Build, ungoogled-chromium) Arch Linux (64-bit)`

**Comment by pdf** [comment]
> Can't test atm but might be an issue with chrome.tabs api, try changing [lines 125-127](https://github.com/NeverDecaf/chromium-web-store/blob/09b4423717f261f5da4ba2e4dbbd1dae1674a2a6/src/scripts/util.js#L125) in util.js from `msgHandler({ newTabUrl: crx_url, });` to `window.open(crx_url, "_blank");`

This resolves the issue here.

**Comment by 0x21D8** [comment]
@kinoegit Can you please test to see if you can update the extension when it's disabled? Your extension should update successfully if you disable the extension you are updating.

**Comment by kinoegit** [comment]
Sure, as soon the next update is due

**Comment by cnleo** [comment]
Same here (manjaro, ungoogled-chromium) 

> @kinoegit Can you please test to see if you can update the extension when it's disabled? Your extension should update successfully if you disable the extension you are updating.

Works! Nice Updates of Extensions.

**Comment by ThisNekoGuy** [comment]
> Your extension should update successfully if you disable the extension you are updating.

Didn't work for me

**Comment by kinoegit** [comment]
Didn't work for me either.

**Comment by blap** [comment]
I don't know how, but an update reset my "chrome://flags/#extension-mime-request-handling" to "default". I changed the "flag chrome://flags/#extension-mime-request-handling" to "Always prompt for install" and works again.

**Comment by ThisNekoGuy** [comment]
> I don't know how, but an update of my ungoogled Chromium reset my "chrome://flags/#extension-mime-request-handling" to "default". I changed the "flag chrome://flags/#extension-mime-request-handling" to "Always prompt for install" and works again.

I tried this and it doesn't work for me. (122.0.6261.111)

**Comment by dm17** [comment]
Is this the same issue that where it successfully detects and starts trying to add extensions but then they get stuck in downloads as "adding to chromium" - while the download spins forever? It open happens with some extensions, however.

**Comment by wctrl** [comment]
Up, same here ^

**Comment by kinoegit** [comment]
It's still the same here too: Version 125.0.6422.60

**Comment by dm17** [comment]
Update on my experience with this issue: basically some restarts and retries of extension updates eventually gets them installed. It still only happens sometimes and it isn't clear what can cause extension download to hang / never complete. If you're having this issue, then try restarting UG and clicking the `chromium web store` button again to trigger the updates.

**Comment by ThisNekoGuy** [comment]
In my experience, it's consistent enough (in normal usage, not brute force attempts - though I have tried that) that I've never once gotten it to go back to its normal behavior since this issue began.

**Comment by waldner** [comment]
Very consistent for me too. Extension remain stuck in "downloading". The right click + "update all extensions" trick does work for me though. Ungoogle chromium 125.0.6422.76.

**Comment by NeverDecaf** [comment]
> try changing [lines 125-127](https://github.com/NeverDecaf/chromium-web-store/blob/09b4423717f261f5da4ba2e4dbbd1dae1674a2a6/src/scripts/util.js#L125) in util.js from `msgHandler({ newTabUrl: crx_url, });` to `window.open(crx_url, "_blank");`

Does this fix/workaround work for any of you? @ThisNekoGuy @waldner @kinoegit

**Comment by kinoegit** [comment]
I'd like to try it, but i'm a noob so please bear with me.. I'd need instructions even with that tiny bit of code, especially how to build after changing those line(s) in user.js

**Comment by waldner** [comment]
@NeverDecaf can't test right now because I don't have any extension needing update, will test ASAP.

@kinoegit: decompress the .crx file into a folder (it's a zip file), make the suggested change to file `scripts/util.js`, then use "load unpacked" to load the extension from the folder where you decompressed it.

**Comment by NeverDecaf** [comment]
Okay, don't worry about testing the above fix. Instead let me make sure I fully understand the issue first:
1. The problem is: installing any extension from the popup menu or web store downloads the CRX instead of prompting to install the extension.
2. The flag `#extension-mime-request-handling` has been set to `Always prompt for install`
3. The `Always download CRX files` checkbox in chromium web store options is *not* checked.

If all of these are true, then I've prepared 2 slightly modified versions of the extension you can try and see if they fix the issue:
[cws-test-A.zip](https://github.com/NeverDecaf/chromium-web-store/files/15447807/cws-test-A.zip)
[cws-test-B.zip](https://github.com/NeverDecaf/chromium-web-store/files/15447808/cws-test-B.zip)
Please test A first and only try B if A doesn't work.

Notes for posterity: 
Both versions only modify [this line](https://github.com/NeverDecaf/chromium-web-store/blob/09b4423717f261f5da4ba2e4dbbd1dae1674a2a6/src/scripts/background.js#L153), A and B remove the `tabs.update` and B sets `active: true` I'll also mention that I have a vague memory of chromium disallowing CRX installs from most URLs (which would cause the behavior described by this issue), it's possible that the [build](https://github.com/macchrome/winchrome/) I'm using has been compiled with a special patch to make this possible, though I'm fairly certain that patch would be the one that adds the `#extension-mime-request-handling` flag in the first place...

**Comment by waldner** [comment]
My experience is that a background tab is opened, the extension gets downloaded (because I see the file appears on disk), but then the download icon keeps spinning, the download never finishes, and it cannot even be interrupted by clicking on the X button.

**Comment by NeverDecaf** [comment]
That's really strange... it sounds like a browser issue that's independent of this extension. The only thing that happens when you update an extension by clicking in the popup is that your browser opens a url in a new tab. Here is the uBlock url that would open, for example: [https://clients2.googleusercontent.com/crx/blobs/AcO95oh11uHb5009Xya0VZQmSlSj81IfJLi8Ai01-01SLLk5PKQnNmaKxflEjToRfXpzcGcUuUBDdER4P_SJ1DmeQURAwBPqfmHtnKScv2U2qGj9RQNEUcqhZ241tHg10Vf0AMZSmuWQVmmt0hbH8B_6jziS-MOD5cTcxg/CJPALHDLNBPAFIAMEJDNHCPHJBKEIAGM_1_58_0_0.crx](https://clients2.googleusercontent.com/crx/blobs/AcO95oh11uHb5009Xya0VZQmSlSj81IfJLi8Ai01-01SLLk5PKQnNmaKxflEjToRfXpzcGcUuUBDdER4P_SJ1DmeQURAwBPqfmHtnKScv2U2qGj9RQNEUcqhZ241tHg10Vf0AMZSmuWQVmmt0hbH8B_6jziS-MOD5cTcxg/CJPALHDLNBPAFIAMEJDNHCPHJBKEIAGM_1_58_0_0.crx)
Can you try visiting this url in your browser to see if it prompts for install correctly?

**Comment by waldner** [comment]
Yes that works and I'm prompted to install it. As soon as some extension need updating, I'll test your new version of the addon.

**Comment by waldner** [comment]
As a matter of fact, one addon became updatable shortly after I wrote this, so I tested with the original cws extension and I got the buggy behavior; I then uninstalled and installed cws-test-A and that worked. Unfortunately I don't have another updateble addon now, so I couldn't test cws-test-B. But cws-test-A seemed to work fine.

**Comment by apprehensions** [comment]
Had this issue, using the [cws-test-A.zip](https://github.com/NeverDecaf/chromium-web-store/files/15447807/cws-test-A.zip) variant of the extension fixed it.

**Comment by NeverDecaf** [comment]
Good to hear! This seems to be an issue with `chrome.tabs.update` but I'm not sure that method is needed in the first place. I'll wait for maybe one more person to confirm that test A works then I'll update chromium web store with the fix.

I believe I was using `chrome.tabs.update` to circumvent an issue with `Update all extensions` where only one of the pending updates would be downloaded. MV3 has changed a lot since then and "update all" was a hack to begin with so it wouldn't surprise me to find that this workaround doesn't do anything anymore.

**Comment by ljford7** [comment]
Just chiming in that A fixed it for me as well (couldn't download any themes from the store).

**Comment by waldner** [comment]
Just had a chance to test B, and it worked too.

However (don't know if it might be related, so let me know if you want a separate issue opened for this), sometimes I see that number in the the red badge with the updateble addons count does not decrease even adter an addon has been updated. Happens with A and B as well.

**Comment by vodkapmp** [comment]
Also just chiming in, A fixed the issue for me.

**Comment by NeverDecaf** [comment]
> sometimes I see that the number in the the red badge with the updateble addons count does not decrease even after an addon has been updated.

Just a quirk of how updates are handled, see #4

**Comment by presageroutlook** [comment]
chrome.9oo91e.qjz9zk is blocked; no matter how you install or follow instructions to t he letter, this NEVER works.  I am sick of ungoogled chromium.
