### ISSUE TITLE
Bookmarks Menu is always in the list to update

### ISSUE THREAD

**Issue by perfect7gentleman** [NeverDecaf/chromium-web-store#20]
https://chrome.google.com/webstore/detail/bookmarks-menu/ffmdedmghpoipeldijkdlcckdpempkdi

IMO, the problem is that different versioning is used. 2020.02.02.1 is in WebStore and 2020.2.2.1 is in Extensions tab.

**Comment by NeverDecaf** [comment]
This seems to be happening because the version string used by that extension is invalid according to [the documentation](https://developer.chrome.com/apps/manifest/version). Specifically, `A couple of rules apply to the integers: they must be between 0 and 65535, inclusive, and non-zero integers can't start with 0.` It appears chromium just strips the leading zeroes instead of rejecting the version number, which leads to this mismatch.

chromium-web-store currently just compares the 2 strings without any regard for the rules or even whether the "new" version number is higher than the old. I will implement the version comparison chromium appears to use (split by '.' and convert to int) which should fix your problem and prevent any accidental downgrades in the future.
