### ISSUE TITLE
why access to browsing history?

### ISSUE THREAD

**Issue by chaosmonk1** [NeverDecaf/chromium-web-store#26]
The other permissions requested by this extension, ("Manage your downloads" and "Manage your apps, extensions, and themes") make sense, but why "Read your browsing history"?  What functionality of the extension requires this?

**Comment by NeverDecaf** [comment]
The "tabs" permission implicitly requires browsing history. The only function I am using from the tabs API is [chrome.tabs.create()](https://developer.chrome.com/extensions/tabs#method-create). I was unaware at the time that this would prompt to "Read your browsing history". I will try to find a workaround that doesn't require the tabs API, but it may not exist.

In order to trick Chromium into prompting for installation of non-Chrome Web Store extensions, the crx file is first downloaded then opened via a `file:///` URL. Formerly the URL was opened with window.open() which produced an error stating `Not allowed to load local resource` (#25). The workaround I am using is to use chrome.tabs.create() in place of window.open(). This is the only instance where the tabs API is used, which you can verify by searching the source.

**Comment by NeverDecaf** [comment]
It seems the "tabs" permission isn't actually needed to use many features of the API, despite the documentation stating otherwise (see: [this stackoverflow answer](https://stackoverflow.com/a/30395968)). I've removed the permission from manifest.json which should prevent the browsing history prompt.

**Comment by chaosmonk1** [comment]
Awesome, thanks!
