### ISSUE TITLE
Chrome deletes CWS.crx file gotten from extention

### ISSUE THREAD

**Issue by AplhaSlayer1964** [NeverDecaf/chromium-web-store#38]
Whenever I download the chrome web store .crx file from the extension Chrome seems to delete it after downloading. Getting it from the releases page is fine. It’s only when getting it from the extension. using un google chromium Version 85.0.4183.121 (Developer Build) (64-bit)

**Comment by NeverDecaf** [comment]
Are you able to install chromium-web-store by dragging and dropping the CRX onto your browser or are you forced to use the `Load unpacked` workaround?

I ask because the hack I use to install non-CWS extensions from the popup is to download the file and then open it in the browser using a `file:///` URL, which mimics the drag-and-drop operation. Chrome's default behavior is to fail and delete any non webstore CRX that you attempt to install in this way, similar to what you are experiencing. If you have not set the `#extension-mime-request-handling` flag, then changing it should fix this issue, otherwise you may be missing a patch in your build which makes this hack possible.

**Comment by AplhaSlayer1964** [comment]
I had not set that flag. Can't really check now as I've already updated but what you described seemed to be the problem.

**Comment by theodorebailey** [comment]
Huge, saved me some pain. Drag and dropping the ".crx" file from chrome to chromium worked a treat.
