### ISSUE TITLE
Link to Chrome Web Store

### ISSUE THREAD

**Issue by erazemk** [NeverDecaf/chromium-web-store#40]
Currently the extension doesn't link to the Chrome Web Store. I think it would be more user friendly to add a link to the store in the menu when right clicking, so that the user doesn't have to manually search for and find the store.

Is there a philosophical reason for not including this or has this just not been requested yet?

**Comment by NeverDecaf** [comment]
1. I don't want to further confuse developers or users into thinking `chromium-web-store` only works for Chrome Web Store hosted extensions (what happened in #34), since it does in fact work for all extensions hosted anywhere so long as an `updates.xml` is provided.
2. I don't want to encourage the use of the Chrome Web Store or Google services in general, if I can avoid doing so I will. (You could all this the philosophical reason, though I don't feel that strongly about this and would be willing to add a link if it's strongly requested.)

Those things aside, finding the store is just a search away as you said, so I feel this is unnecessary.

**Comment by erazemk** [comment]
Fair enough, thanks for explaining :)
