### ISSUE TITLE
Warn Users if an Installed Extension is Removed from the Web Store

### ISSUE THREAD

**Issue by FluorescentGreen5** [NeverDecaf/chromium-web-store#41]
So I noticed on someone's installation of Google Chrome that they had a notification that Nano Defender was removed due to violating ToS (the extension got new developers and they were putting spyware in it). Is it possible to add a feature to allow users to give CWS a list of extensions to check for their removal from the web store?

**Comment by NeverDecaf** [comment]
This is possible and useful but I'm not exactly sure how to present this information to the user. Here's a quick mock-up of my current idea, the checkbox would allow you to ignore the extension just like you can do in options. I think this is not intuitive, maybe if there were instead a separate section at the bottom of the popup for removed extensions? Let me know if you have any ideas.
![image](https://user-images.githubusercontent.com/19150416/103038797-58332300-453d-11eb-8b0c-6afe2e9f922c.png)

**Comment by FluorescentGreen5** [comment]
Yeah, a separate section at the bottom saying "Nano Defender was removed from the Chrome Web Store, possibly due to ToS violation." along with highlighting the offending extensions with an exclamation mark like in the mock-up would work. Maybe add the word "Ignore" next to the checkbox so that people know what it does.

**Comment by NeverDecaf** [comment]
I suppose the text is necessary to make it not confusing, maybe I'll add a header with something like `The following extensions have been removed from the chrome web store, check the box to ignore future updates`.

However, I've thought of an issue with this system: extensions are sometimes removed from the store **temporarily**. If this is the case you likely don't want to ignore updates forever. What about this solution instead:
- No checkbox or option to ignore extensions, instead have an `OK`, `✓` or `❌` button just to confirm that you have seen the message. Clicking the button would simply clear the notification.

**Comment by NeverDecaf** [comment]
Here is my current design:
![image](https://user-images.githubusercontent.com/19150416/103070545-b7ba1e80-458f-11eb-8b09-2222251943b0.png)
There is a tooltip on the red-bordered div that reads `These may have been removed due to a violation of the Terms of Service and may be malicious.` but most users will probably never see it. There is no real reason the text can't be longer besides looking odd:
![image](https://user-images.githubusercontent.com/19150416/103070715-1384a780-4590-11eb-914f-07a5a6e070ca.png)
but I'm not sure how much explanation is needed. As far I'm aware, extensions are frequently removed from the store for reasons besides being malicious (inactivity, false flags/reports, etc) so I want to avoid scaring the user into thinking this means the extension is certainly a safety risk. I'm currently favoring the first option (screenshot).
