### ISSUE TITLE
closing tab cause not update extension

### ISSUE THREAD

**Issue by jacob755** [NeverDecaf/chromium-web-store#51]
ok not sure for me or everyone
i have two open tab now check for update  with chromium-web-store then clicking to update
now  extension getting downloaded i close tab  that have focus when check for update. now add  extension  popup wont show and extension wont update

thanks

**Comment by NeverDecaf** [comment]
This is probably caused by another extension or flag you have set which interferes with `target='_blank'` or you did not set the `chrome://flags/#extension-mime-request-handling` flag, or you are using a browser which does not support direct installation of CRX files.

Closing since nobody has reported the same issue and I cannot reproduce this.
