### ISSUE TITLE
Limit frequency of extension update checks?

### ISSUE THREAD

**Issue by GalacticSun** [NeverDecaf/chromium-web-store#53]
Any chance of providing a setting that would allow us to limit how frequently this checks for extension updates on the Chrome Store, ideally from once every hour to once per day or even once per week?
Thanks, and keep up the great work.

**Comment by NeverDecaf** [comment]
This feature is something I plan(ed) to add, but it would actually require a major rewrite/addition of new code due to the way update checking currently works, and I don't have time to work on it right now. To briefly describe the issue:
- Update checks are currently done hourly (and on startup) if you have the option enabled, the result of this update is used only to change the number displayed on the icon.
- When the popup is clicked, an update check is done immediately and used to populate the list in the popup.
- To enforce long update intervals (say, once a day) the extension would need to store both the last update time and (more importantly) the *results* of the last update. It would then also need to load these results into the popup later.
- Both the storing/loading of the updates list would require quite a bit of new code on top of the work to allow variable times to begin with.

Because of all this I recommend just unchecking the `Automatically check for extension updates` option and checking for updates manually (by clicking the icon) if you don't want to be contacting Google every hour.
So to answer your question, yes there's a chance but I wouldn't expect it anytime soon (from me).

**Comment by GalacticSun** [comment]
Okay, sounds good.  I will uncheck that automatic update setting in the meantime.  Thanks!

**Comment by NeverDecaf** [comment]
It turns out chrome.alarms actually persist across sessions, which will make this much simpler to implement.

**Comment by NeverDecaf** [comment]
Added in 1.3.0
