### ISSUE TITLE
Bug checking update of Bypass Paywalls Chrome Clean

### ISSUE THREAD

**Issue by DarknessKiller123** [NeverDecaf/chromium-web-store#59]
When I am checking for updates with the extension, always appear this error:
Bypass Paywalls Clean update failed.
This is the link of the extension: https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean
I also check the update.xml of this extension and it look fine: https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean/-/blob/master/updates.xml

**Comment by NeverDecaf** [comment]
This is caused by CORS blocking requests to external sites from within the extension (more details [here](https://developer.chrome.com/docs/extensions/mv2/xhr/)). 
The easy fix would be to add `https://*/` to "permissions" in manifest.json, but this will grant and prompt users with a message about this app having access to `Your data on all the websites you visit` which I would like to avoid. I will add something more selective where the user can grant permissions for a specific site (when the update fails, most likely).
