### ISSUE TITLE
Installing and usage issue

### ISSUE THREAD

**Issue by TNCS-git** [NeverDecaf/chromium-web-store#6]
Ungoogled Chrome ver:  78.0.3904.108-1 WinX64
--
Have the following two issue:
1. The .crx will not install even if I enable the Developer's option under extension. I had to rename to .zip file instead and click and drag to install. Kindly verify if this is correct?

2. After PC reboot/restart, the webstore extension will disappear from Ungoogled Chrome.

**Comment by NeverDecaf** [comment]
I personally have not experienced this issue on builds from https://github.com/macchrome/winchrome/releases; I can install the .crx by drag-and-drop. I am currently using the latest build (78.0.3904.108). 
There is an open issue that sounds very similar to your problem here: [https://github.com/Eloston/ungoogled-chromium/issues/834](https://github.com/Eloston/ungoogled-chromium/issues/834) perhaps you can find a solution that works for you in the comments.

I would first try unzipping the file to a folder and then using "Load Unpacked" with developer mode enabled to install.

**Comment by lastweakness** [comment]
Neither of the issues effect me

**Comment by NeverDecaf** [comment]
Closing this as it seems to be an issue with the browser itself rather than the extension.
