### ISSUE TITLE
Not working on Chromium 87

### ISSUE THREAD

**Issue by Zoooook** [NeverDecaf/chromium-web-store#65]
I'm on Ungoogled Chromium Version 87.0.4280.88 (Official Build) (64-bit). The button to add an extension does not appear in the chrome web store. If I right click and select Add to Chromium, nothing happens, nothing appears in the network tab of dev tools, nothing is output in the console. I tried this in incognito mode with all other extensions turned off. chrome://flags/#extension-mime-request-handling is set to Always prompt for install.

**Comment by NeverDecaf** [comment]
Sorry for the very late reply, I somehow missed this issue. 🙏
If you are still having problems you can go to `chrome:extensions` and click `Inspect views
background page`. If there is an error while trying to download an extension it might appear here. Unfortunately these issues tend to be caused by something about the way your particular version of chromium was compiled or is currently configured so chances are there isn't much I can do to help.

**Comment by Zoooook** [comment]
Ah nothing appears there either. Oh well, I can just add extensions the hard way then. Thanks.
