### ISSUE TITLE
Cannot install extensions from Chrome web store

### ISSUE THREAD

**Issue by mark-franz** [NeverDecaf/chromium-web-store#70]
Hi, I installed 
- Chromium 89.0.4389.114 (Developer Build, ungoogled-chromium) (64-Bit)
- Chromium Web Store v. 1.4.0

Settings: 
- Access to web sites including https://chrome.google.com/* and https://clients2.google.com/* is allowed.
- chrome://flags/#extension-mime-request-handling is set to **Always prompt for install**.

In Chromium, when I click to open Chrome Web Store, the new tab is blank. 
(In the adress line it first says **about:blank**. 
When I click into the address line, I see this URL: **trk:09:https://chrome.9oo91e.qjz9zk/webstore/category/extensions**)

When I open a new tab, I can see a blue icon pointing to https://chrome.9oo91e.qjz9zk/webstore?hl=de
When I click to open it, I get the message (in German): 

In German: 
> chrome.9oo91e.qjz9zk ist gesperrt
> Anfragen an den Server wurden durch eine Erweiterung blockiert.
> Deaktivieren Sie Ihre Erweiterungen.
> ERR_BLOCKED_BY_CLIENT
> 

In English (looked up on the web): 
> chrome.9oo91e.qjz9zk ist blocked
> Requests to the server have been blocked by an extension.
> Try disabling your extensions.
> ERR_BLOCKED_BY_CLIENT
>

**Comment by NeverDecaf** [comment]
I'm not sure if this is helpful but I believe all requests to `chrome.9oo91e.qjz9zk` are blocked in ungoogled-chromium. I don't know why you are being redirected to this domain though, have you tried directly visiting [https://chrome.google.com/webstore/category/extensions?hl=de](https://chrome.google.com/webstore/category/extensions?hl=de)?

**Comment by TysonVanDeVelde** [comment]
Hi, I can confirm that this behavior is caused by Ungoogled Chromium, not this extension. The blank tab occurs when trying to access the Chrome Web Store by clicking a link within the browser, e.g. the hamburger menu on [chrome://extensions/](chrome://extensions/).

Chromium by default contains many links to Google domains, so to protect the privacy of users, Ungoogled Chromium replaces all internal Google links with with .9jz9zk URLs, which are blocked automatically to avoid creating unnecessary requests to your DNS. You can still visit Google domains manually or through browsing on the Internet. You just won't be sent there by the links within the browser.

Because of this, I have started keeping a folder in my bookmarks containing links to various administrative URLs: [chrome://flags](chrome://flags), [Chrome Web Store](https://chrome.google.com/webstore/category/extensions), [chrome://extensions](chrome://extensions), [Violentmonkey Dashboard](chrome-extension://jinjaccalgkegednnccohejagnlnfdag/options/index.html), etc. You can find a list of Chrome URLs at [chrome://chrome-urls/](chrome://chrome-urls/). I find this the most convenient way to use Ungoogled Chromium.

**Comment by mark-franz** [comment]
Thanks a lot, that's helpful!

**Comment by candrapersada** [comment]
Hi,

I'm the author of an extension that supports connecting to Google OAuth for syncing bookmarks via an encrypted file in Google Drive. Using Google OAuth in ungoogled-chromium doesn't work however, as google says:
https://user-images.githubusercontent.com/36833664/110196580-11847200-7e78-11eb-8738-a37213e14fb6.png

Is there anything I can do to make this work, or is this by design / won'tfix for you folks?

see floccusaddon/floccus#847

**Comment by NeverDecaf** [comment]
I think you are in the wrong place, this is just a chrome extension. You should open an issue [here](https://github.com/Eloston/ungoogled-chromium/issues).

**Comment by pieterhouwen** [comment]
> i get this error now, after i managed to install this store extensions via some 'manifest' and 'missing proof' errors...:
> "Apps, extensions and user scripts cannot be added from this website"

Take a look at this: https://github.com/Eloston/ungoogled-chromium/issues/1556#issuecomment-890580858

**Comment by jimsy3** [comment]
yes, now is fixed thanks
