### ISSUE TITLE
Apps, extensions and user scripts cannot be added from this website

### ISSUE THREAD

**Issue by pieterhouwen** [NeverDecaf/chromium-web-store#71]
I'm greeted with this error every time I try to update a plugin/extension using right click -> Update all extensions on the Chromium Web Store plugin icon.

Is there any additional information that you need and how can I get that?

PS: Debug mode is on at chrome://extensions

**Comment by NeverDecaf** [comment]
Which browser and version?

**Comment by pieterhouwen** [comment]
Version 91.0.4472.124 (Official Build, ungoogled-chromium) (64-bit)

**Comment by NeverDecaf** [comment]
If you are using the builds from woolyss' site I am using the same browser as you and not experiencing this problem.
This error message normally appears in chrome when trying to install any extension from outside the Chrome Web Store. I'm not sure why you are getting this in ungoogled chromium. 
Does this error only occur when you update all, or does it happen when installing any individual extensions? My guess is that one of your extensions is not from the chrome web store and is triggering this warning. If you can narrow it down to which one that should make this easier to debug. If you are getting this when trying to install *any* extension then it may be caused by a setting or some other extension you are using.

As a quick test can you also try to download a web store crx directly (you can try this link: [https://clients2.googleusercontent.com/crx/blobs/Acy1k0bE8PV2ezmDj7kQqZ0Y6t6hd458jHiPeEVjvYePSFjLjIf_7Z5jvDLaT5UV5_AZPiBCFWpsLbJmoMitN7bemC3vEIbMwSxrkX6-qjr-OVDF9gK9AMZSmuV0ysjlpe0fjjNhI9WiDM8PhnujcQ/extension_1_4_0_0.crx](https://clients2.googleusercontent.com/crx/blobs/Acy1k0bE8PV2ezmDj7kQqZ0Y6t6hd458jHiPeEVjvYePSFjLjIf_7Z5jvDLaT5UV5_AZPiBCFWpsLbJmoMitN7bemC3vEIbMwSxrkX6-qjr-OVDF9gK9AMZSmuV0ysjlpe0fjjNhI9WiDM8PhnujcQ/extension_1_4_0_0.crx)) and see if you still get the error? (You should be prompted to install uMatrix upon clicking this if you have the `extension-mime-request-handling` flag set.)

**Comment by pieterhouwen** [comment]
When I try a direct install (opening the .crx with chrome.exe) I'm getting this error, dragging and dropping seems to work.

Currently installed extensions:

- Bypass Paywalls
- Behind The Overlay
- NoScript
- Psono
- uBlock Origin
- Unpaywall
- Video DownloadHelper

**Comment by NeverDecaf** [comment]
If the direct crx link doesn't work, this is probably an issue with your browser.
I assume you are *not* using [macchrome](https://github.com/macchrome/winchrome)'s build, which most likely modifies something extra to disable chromium's default behavior of disallowing any non-webstore crx downloads.

I don't know enough about ungoogled chromium to offer any more help than this, but you can try searching the ungoogled chromium wiki or issue tracker for a solution.

**Comment by pieterhouwen** [comment]
Fixed :)

For future reference: I didn't set the chrome://flags/#extension-mime-request-handling to Always prompt for install.
