### ISSUE TITLE
"Add to Chromium" opens a download-prompt instead of installing the extension

### ISSUE THREAD

**Issue by Switch123456789** [NeverDecaf/chromium-web-store#92]
The title explains the whole issue.
I am using Ungoogled Chromium (99.0.4844.51 | 64bit) on Manjaro Budgie.
I tried installing it with both methods (drag&drop and load unpacked).
I also changed the flag `extension-mime-request-handling` to `always prompt for install`

**Comment by NeverDecaf** [comment]
Chrome's extension API doesn't allow for the direct installation of other extensions so chromium-web-store uses a hack to install them (opening the CRX in a new tab and letting your browser handle the automatic installation prompt); if this auto-install isn't working in your browser (usually fixed by setting the flag you already set) I don't think anything can be done on the side of this extension to fix it.

**Comment by Switch123456789** [comment]
I was able to fix/workaround it by installing "ungoogled-chromium" & "chromium-extension-web-store" through the AUR repository. Before it was installed with flatpak.

**Comment by PF4Public** [comment]
I also stumbled upon this issue and it seems that it has something to do with the extension size.
1. [TinEye Reverse Image Search](https://chrome.google.com/webstore/detail/tineye-reverse-image-sear/haebnnbpedcbhciplfhjjkbafijpncjl) installs without issues
2. [Search by Image](https://chrome.google.com/webstore/detail/search-by-image/cnojnbdhbhnkbcieeekonklommdnndci) does not

First one is 35.64KiB and the second is 745KiB. I also couldn't install the latter via direct link.
